### ISSUE TITLE
Running doxygen.py gives SyntaxError on Doxyfile content

### ISSUE THREAD

**Issue by jbltx** [mosra/m.css#110]
I have followed the steps described [here](https://mcss.mosra.cz/documentation/doxygen/), unfortunately when I run the command 

```sh
./doxygen.py path/to/your/Doxyfile-mcss
```
an error occurs when parsing the content of the file 

```sh
Traceback (most recent call last):
  File "python.py", line 2632, in <module>
    module = SourceFileLoader(name, args.conf).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../../../Doxyfile-mcss", line 1
    @INCLUDE                = Doxyfile
                            ^
SyntaxError: invalid syntax
```

Did I miss something ?
Thanks

> Python 3.7.3
> Doxygen 1.8.16
> Mac OSX 10.14.6 (Mojave)

**Comment by jbltx** [comment]
Nevermind, not sure what I did before but the command works as expected. I close the issue.

**Comment by mosra** [comment]
Looks like calling `./python.py` instead of `./doxygen.py` :)
