### ISSUE TITLE
pybind11 with nested class in a base class gives AttributeError

### ISSUE THREAD

**Issue by wojdyr** [mosra/m.css#192]
I get such a traceback if I have a nested class in a class that is then inherited by another class.
```
Traceback (most recent call last):
  File "m.css/documentation/python.py", line 2710, in <module>
    run(os.path.dirname(os.path.abspath(args.conf)), config, templates=os.path.abspath(args.templates))
  File "m.css/documentation/python.py", line 2502, in run
    modules_to_crawl += crawl_module(state, path, object)
  File "m.css/documentation/python.py", line 694, in crawl_module
    crawl_class(state, subpath, object)
  File "m.css/documentation/python.py", line 425, in crawl_class
    crawl_class(state, subpath, object)
  File "m.css/documentation/python.py", line 389, in crawl_class
    if id(previous_entry.object) == id(class_): break
AttributeError: 'types.SimpleNamespace' object has no attribute 'object'
```

In pydoc it looks like this:
```
    class FloatGridBase(pybind11_builtins.pybind11_object)
     |  Data and other attributes defined here:
     |  
     |  Point = <class 'gemmi.FloatGridBase.Point'>

    class FloatGrid(FloatGridBase)
     |  Data and other attributes inherited from FloatGridBase:
     |  
     |  Point = <class 'gemmi.FloatGridBase.Point'>
```

**Comment by mosra** [comment]
(Sorry for *embarrassingly* late replies, finally got a chance to get back to this project.)

Heh, took me a while to see what's going on. A duplicated class checker was looking for where the class was defined first to print a warning about the same class being present in two different places in the docs, and it didn't skip enum values (which aren't really objects) when doing the `id()` comparisons. Added a regression test in 04f1375b104553f4c97beb397229cf6b25585243, fixed in 0b6497481836a8e9ac57b4e8ee7cb208a2a371d8.
