### ISSUE TITLE
break when using c++ friend class 

### ISSUE THREAD

**Issue by Marco-Israel** [mosra/m.css#205]
```
class MyClass : ISomeInterface {

public:
MyClass();
~MyClass();
void somefunction(void);
...

frind class myFriend;
}
```

breaks when building doxygen mcss. Normal doxygen html without mcss can build.

```
Traceback (most recent call last):
  File ".../documentation/doxygen.py", line 3859, in <module>
    run(state, templates=os.path.abspath(args.templates), wildcard=args.wildcard, hindex_pages=args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "../documentation/doxygen.py", line 3716, in run
    parsed = parse_xml(state, file)
  File ".../documentation/doxygen.py", line 2988, in parse_xml
    func = parse_func(state, memberdef)
  File "../documentation/doxygen.py", line 1965, in parse_func
    if signature.endswith('=default'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by mosra** [comment]
(Sorry for *embarrassingly* late replies, finally got back to this project and to the final boss that is Doxygen.)

#189 got merged as c7ee89e74cf96323b7bf14d4c7535b6867d57868, so this should be fixed now.
