### ISSUE TITLE
Doxygen Theme AssertionError parsing class xml

### ISSUE THREAD

**Issue by glfmn** [mosra/m.css#45]
Similar to the error that shows up in #33 except using the default doxygen config does not solve the issue.  As far as I can tell, there's something unexpected in the xml but I can't determine what it is.

```
DEBUG:root:Parsing classmodel_1_1Model.xml
WARNING:root:classmodel_1_1Model.xml: no filename attribute in <programlisting>, assuming C++
WARNING:root:classmodel_1_1Model.xml: inline code has multiple lines, fallback to a code block
WARNING:root:classmodel_1_1Model.xml: no filename attribute in <programlisting>, assuming C++
WARNING:root:classmodel_1_1Model.xml: inline code has multiple lines, fallback to a code block
WARNING:root:classmodel_1_1Model.xml: no filename attribute in <programlisting>, assuming C++
WARNING:root:classmodel_1_1Model.xml: no filename attribute in <programlisting>, assuming C++
WARNING:root:classmodel_1_1Model.xml: inline code has multiple lines, fallback to a code block
WARNING:root:classmodel_1_1Model.xml: no filename attribute in <programlisting>, assuming C++
Traceback (most recent call last):
  File "./mcss/doxygen/dox2html5.py", line 2948, in <module>
    run(doxyfile, os.path.abspath(args.templates), args.wildcard, args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "./mcss/doxygen/dox2html5.py", line 2866, in run
    parsed = parse_xml(state, file)
  File "./mcss/doxygen/dox2html5.py", line 2254, in parse_xml
    func = parse_func(state, memberdef)
  File "./mcss/doxygen/dox2html5.py", line 1517, in parse_func
    func.description, templates, params, func.return_value, func.return_values, func.exceptions, search_keywords, func.is_deprecated = parse_func_desc(state, element)
  File "./mcss/doxygen/dox2html5.py", line 1364, in parse_func_desc
    parsed = parse_desc_internal(state, element.find('detaileddescription'))
  File "./mcss/doxygen/dox2html5.py", line 659, in parse_desc_internal
    assert not parsed.templates and not parsed.params and not parsed.return_value
AssertionError
```
Gist of the xml: https://gist.github.com/glfmn/eeebe1237920d5f81c92af5194c045de

**Comment by glfmn** [comment]
The warnings are referring to my use of the doxygen `\snippet` feature

**Comment by mosra** [comment]
Hi, this is probably due to `@param` being after `@section` inside function description. Having `@section` inside function description is not really supported now and generates weirdly styled output at the moment, but I'll look into that and see what can be done.

Workaround possibilities until I fix this:

- use Markdown headings (`##`) instead of `@section`
- move the `@param` (and `@return` and other) before the `@section`

**Comment by glfmn** [comment]
Oh nice catch!  I saw that mentioned in the documentation but I guess I neglected to check for myself.  Thanks for the swift response!

**Comment by mosra** [comment]
Should be fully implemented in bbb55becae9d175b2362530d788dced2758afcb0. Please reopen if you still encounter problems :)

**Comment by Serkan-devel** [comment]
@mosra OP can't re-open this issue if you have closed it

**Comment by mosra** [comment]
Really? Interesting, I thought that was possible.

Then at least complain loudly, I'll hear ya ;)
