### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by dhanjit** [mosra/m.css#51]
```
Traceback (most recent call last):
  File "/home/dhanjit.d/dump/m.css/doxygen/dox2html5.py", line 3040, in <module>
    run(doxyfile, os.path.abspath(args.templates), args.wildcard, args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "/home/dhanjit.d/dump/m.css/doxygen/dox2html5.py", line 2954, in run
    parsed = parse_xml(state, file)
  File "/home/dhanjit.d/dump/m.css/doxygen/dox2html5.py", line 2059, in parse_xml
    compound.description, templates, compound.sections, footer_navigation, example_navigation, search_keywords, compound.is_deprecated = parse_toplevel_desc(state, compounddef.find('detaileddescription'))
  File "/home/dhanjit.d/dump/m.css/doxygen/dox2html5.py", line 1417, in parse_toplevel_desc
    parsed = parse_desc_internal(state, element)
  File "/home/dhanjit.d/dump/m.css/doxygen/dox2html5.py", line 668, in parse_desc_internal
    parsed = parse_desc_internal(state, i)
  File "/home/dhanjit.d/dump/m.css/doxygen/dox2html5.py", line 668, in parse_desc_internal
    parsed = parse_desc_internal(state, i)
  File "/home/dhanjit.d/dump/m.css/doxygen/dox2html5.py", line 673, in parse_desc_internal
    assert not parsed.templates and not parsed.params and not parsed.return_value and not parsed.return_values and not parsed.exceptions
AssertionError

```

With some added logging I found that `params`, `return_value` are non empty:

When could this be? The function is quite straightforward (truncated for security reasons)

```
    /** some lines

      \param[in] preset Initialization preset information.
      \param[in] id The id...
      \param[in] leg leg=i means the i'th ...
      be initialized.
      \param[in] symbol_info Basic information like ...

      \return TypeId,...
 some lines...


      Example:
     */
```

So the function is probably not the culprit, but something else. Unable to figure out how...

**Comment by mosra** [comment]
Where do you use `\copydetails`? The following case works (it would also work with `\copydoc`) and it fills the documentation of `foo2()` with everything that's in for `foo()` -- so description of the parameter and description of the return value:

```cpp
/**
@brief A function
@param bar A param.
@return Does not return anything.
*/
void foo(int bar);

/** @copydetails foo */
int foo2(int bar);
```

But in this case:

```cpp
/**
@brief A function
@param bar A param.
@return Does not return anything.
*/
void foo(int bar);

/** @copydetails foo */
int bar;
```

it will assert in the place you mentioned above, because `bar` is a variable, it doesn't have any parameters or a return type. That assertion seems valid to me, why would anybody want to describe a parameter in a variable documentation.

Where do you call `\copydetails`? At which place? How it should behave with those extraneous things? Ignore them? Write an error to the output? I checked what stock Doxygen HTML output has and it just puts everything there, even though it's a variable and not complaining about anything. That seems wrong to me.

**Comment by dhanjit** [comment]
I am using copydetails in a getting start page, where I put details of some important functions under sections.
