### ISSUE TITLE
No styling generated

### ISSUE THREAD

**Issue by jeljaik** [mosra/m.css#61]
Hello there, 

I've followed the instructions in http://mcss.mosra.cz/doxygen/#troubleshooting but the generated html files have no styling whatsoever. The compilation finishes with the following message:

```
Traceback (most recent call last):
  File "./dox2html5.py", line 3041, in <module>
    run(doxyfile, os.path.abspath(args.templates), args.wildcard, args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "./dox2html5.py", line 2955, in run
    parsed = parse_xml(state, file)
  File "./dox2html5.py", line 2060, in parse_xml
    compound.description, templates, compound.sections, footer_navigation, example_navigation, search_keywords, compound.is_deprecated = parse_toplevel_desc(state, compounddef.find('detaileddescription'))
  File "./dox2html5.py", line 1415, in parse_toplevel_desc
    parsed = parse_desc_internal(state, element)
  File "./dox2html5.py", line 784, in parse_desc_internal
    add_css_class=add_css_class)
  File "./dox2html5.py", line 765, in parse_desc_internal
    out.parsed += '<{0}>{1}</{0}>'.format(tag, html.escape(i.text))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
AttributeError: 'NoneType' object has no attribute 'replace'
```

Can anyone give me a hand?  Thanks!
I'm using MacOS 
Python 3.6.4
Doxygen 1.8.14

**Comment by mosra** [comment]
Hi!

Turns out I discovered a very similar crash this afternoon, related to how Doxygen "parses" Markdown headers. Should be fixed with 2eb544cac8b53be176994f92d987e9fed157b076 (you'll get a warning now instead of an assert), see the commit for details about what exactly is Doxygen doing wrong and how to work around it. 

Can you try again with current master and report back? :)

**Comment by mosra** [comment]
Awesome :)
