### ISSUE TITLE
Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by jeljaik** [mosra/m.css#62]
Hello!

I am trying to compile my Doxygen documentation on Ubuntu 16.04 and to do so I have installed Python 3.6 from a PPA, along with pip3.6 and the other dependencies, Latex included. However I'm getting the following error:

```
[...]
(/usr/share/texlive/texmf-dist/tex/latex/graphics/dvips.def))
! Missing number, treated as zero.
<to be read again>
                   f
l.12 \definecolor{m-default}{HTML}{cafe03}

No pages of output.
Transcript written on code.log.

Traceback (most recent call last):
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 3122, in <module>
    run(doxyfile, os.path.abspath(args.templates), args.wildcard, args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 3036, in run
    parsed = parse_xml(state, file)
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 2079, in parse_xml
    compound.description, templates, compound.sections, footer_navigation, example_navigation, search_keywords, compound.is_deprecated = parse_toplevel_desc(state, compounddef.find('detaileddescription'))
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 1426, in parse_toplevel_desc
    parsed = parse_desc_internal(state, element)
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 669, in parse_desc_internal
    parsed = parse_desc_internal(state, i)
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 792, in parse_desc_internal
    add_css_class=add_css_class)
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 872, in parse_desc_internal
    row_data += '<{0}>{1}</{0}>'.format('th' if is_header else 'td', parse_desc(state, entry))
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 1387, in parse_desc
    parsed = parse_desc_internal(state, element)
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 792, in parse_desc_internal
    add_css_class=add_css_class)
  File "/home/jenkins/workspace/m.css/doxygen/dox2html5.py", line 1231, in parse_desc_internal
    depth, svg = latex2svgextra.fetch_cached_or_render('{}'.format(i.text))
  File "/home/jenkins/workspace/m.css/doxygen/../pelican-plugins/latex2svgextra.py", line 111, in fetch_cached_or_render
    out = latex2svg.latex2svg(formula, params=params)
  File "/home/jenkins/workspace/m.css/doxygen/../pelican-plugins/latex2svg.py", line 86, in latex2svg
    return latex2svg(code, params, working_directory=tmpdir)
  File "/home/jenkins/workspace/m.css/doxygen/../pelican-plugins/latex2svg.py", line 105, in latex2svg
    ret.check_returncode()
  File "/home/jenkins/python3.6/lib/python3.6/subprocess.py", line 369, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction', 'nonstopmode', '-halt-on-error', 'code.tex']' returned non-zero exit status 1.
doc/CMakeFiles/dox.dir/build.make:57: recipe for target 'doc/CMakeFiles/dox' failed
make[7]: *** [doc/CMakeFiles/dox] Error 1
CMakeFiles/Makefile2:2116: recipe for target 'doc/CMakeFiles/dox.dir/all' failed
make[6]: *** [doc/CMakeFiles/dox.dir/all] Error 2
CMakeFiles/Makefile2:2123: recipe for target 'doc/CMakeFiles/dox.dir/rule' failed
make[5]: *** [doc/CMakeFiles/dox.dir/rule] Error 2
Makefile:576: recipe for target 'dox' failed
make[4]: *** [dox] Error 2
doc/CMakeFiles/ISAAC-dox.dir/build.make:57: recipe for target 'doc/CMakeFiles/ISAAC-dox' failed
make[3]: *** [doc/CMakeFiles/ISAAC-dox] Error 2
CMakeFiles/Makefile2:1750: recipe for target 'doc/CMakeFiles/ISAAC-dox.dir/all' failed
make[2]: *** [doc/CMakeFiles/ISAAC-dox.dir/all] Error 2
CMakeFiles/Makefile2:1725: recipe for target 'doc/CMakeFiles/dox.dir/rule' failed
make[1]: *** [doc/CMakeFiles/dox.dir/rule] Error 2
Makefile:766: recipe for target 'dox' failed
make: *** [dox] Error 2
```

Can you give me a hand to understand why?

Thanks!

**Comment by mosra** [comment]
Hi,

quick googling revealed that this seems to be [a bug in the latex xcolor package](https://tex.stackexchange.com/questions/274524/definecolorset-of-xcolor-problem-with-color-values-starting-with-f) :/ (ugh, why is *everything* so broken these days? :see_no_evil:)

It's apparently fixed in a later version and it's a problem when colors contain lowercase `f`. Can you apply the following patch (it just uses uppercase `F` instead) and try again?

```diff
diff --git a/pelican-plugins/latex2svgextra.py b/pelican-plugins/latex2svgextra.py
index a71a2a0..6ad1224 100644
--- a/pelican-plugins/latex2svgextra.py
+++ b/pelican-plugins/latex2svgextra.py
@@ -45,13 +45,13 @@ params.update({
 \usepackage{newtxtext}
 
 \usepackage{xcolor}
-\definecolor{m-default}{HTML}{cafe03}
-\definecolor{m-primary}{HTML}{cafe04}
-\definecolor{m-success}{HTML}{cafe05}
-\definecolor{m-warning}{HTML}{cafe06}
-\definecolor{m-danger}{HTML}{cafe07}
-\definecolor{m-info}{HTML}{cafe08}
-\definecolor{m-dim}{HTML}{cafe09}
+\definecolor{m-default}{HTML}{caFe03}
+\definecolor{m-primary}{HTML}{caFe04}
+\definecolor{m-success}{HTML}{caFe05}
+\definecolor{m-warning}{HTML}{caFe06}
+\definecolor{m-danger}{HTML}{caFe07}
+\definecolor{m-info}{HTML}{caFe08}
+\definecolor{m-dim}{HTML}{caFe09}
 """,
     # Zoom the letters a bit to match page font size
     'dvisvgm_cmd': 'dvisvgm --no-fonts -Z 1.25',
@@ -59,13 +59,13 @@ params.update({
 
 # Mapping from color codes to CSS classes. Keep in sync with m.plots.
 _class_mapping = {
-    ('fill=\'#cafe03\'', 'class=\'m-default\''),
-    ('fill=\'#cafe04\'', 'class=\'m-primary\''),
-    ('fill=\'#cafe05\'', 'class=\'m-success\''),
-    ('fill=\'#cafe06\'', 'class=\'m-warning\''),
-    ('fill=\'#cafe07\'', 'class=\'m-danger\''),
-    ('fill=\'#cafe08\'', 'class=\'m-info\''),
-    ('fill=\'#cafe09\'', 'class=\'m-dim\'')
+    ('fill=\'#caFe03\'', 'class=\'m-default\''),
+    ('fill=\'#caFe04\'', 'class=\'m-primary\''),
+    ('fill=\'#caFe05\'', 'class=\'m-success\''),
+    ('fill=\'#caFe06\'', 'class=\'m-warning\''),
+    ('fill=\'#caFe07\'', 'class=\'m-danger\''),
+    ('fill=\'#caFe08\'', 'class=\'m-info\''),
+    ('fill=\'#caFe09\'', 'class=\'m-dim\'')
 }
 
 _patch_src = re.compile(r"""<\?xml version='1\.0' encoding='UTF-8'\?>
```

Thank you!

**Comment by jeljaik** [comment]
Yeah! that was it! Thank you so much for your great work. It's wonderful what you've done and I'm having so much fun playing with it :) The results are stunning!

**Comment by mosra** [comment]
Turns out the above patch actually made the equation coloring broken, I commited a correct version to master as b0330a8785dfa3fa6df705a099f22a6aa1f51f91.

Thanks a lot for the appreciation, that's what keeps me going :+1: :blush: Regarding math equations in particular, there are more features that might not be obvious at first, look here: http://mcss.mosra.cz/admire/math/
