### ISSUE TITLE
dox2html5.py: assertion

### ISSUE THREAD

**Issue by liamstask** [mosra/m.css#92]
I've just run m.css against a reasonably large c++ codebase for the first time, and have run into an assertion (pasted below). a few details:
* doxygen: 1.8.15 installed via binary
* m.css: running from master as of today, a02eeabc7f06cbdcd963a987530f09c2b8f42288

Because the assertion below doesn't contain much context, it's not straightforward to determine what input caused this error - generation was running for ~7 minuets minutes before I hit this. Also, the codebase is private, so not easy to share a minimal snippet :/

Last output before this error was a long sequence of `WARNING:root:md_XYZ_README.xml: ...` warnings, not sure if they're relevant.

I confess I have not yet added any debug printing/output to the script, but I wonder if it's feasible to add a bit more context in the assertion, to at least indicate which input files are implicated?

Please let me know if there's any further info I can provide - thanks.

Assertion:
```
Traceback (most recent call last):
  File "/m.css/doxygen/dox2html5.py", line 3626, in <module>
    run(doxyfile, os.path.abspath(args.templates), args.wildcard, args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "/m.css/doxygen/dox2html5.py", line 3510, in run
    parsed = parse_xml(state, file)
  File "/m.css/doxygen/dox2html5.py", line 2423, in parse_xml
    compound.description, templates, compound.sections, footer_navigation, example_navigation, search_keywords, compound.is_deprecated = parse_toplevel_desc(state, compounddef.find('detaileddescription'))
  File "/m.css/doxygen/dox2html5.py", line 1666, in parse_toplevel_desc
    parsed = parse_desc_internal(state, element)
  File "/m.css/doxygen/dox2html5.py", line 910, in parse_desc_internal
    add_css_class=add_css_class)
  File "/m.css/doxygen/dox2html5.py", line 961, in parse_desc_internal
    parsed = parse_desc_internal(state, li)
  File "/m.css/doxygen/dox2html5.py", line 910, in parse_desc_internal
    add_css_class=add_css_class)
  File "/m.css/doxygen/dox2html5.py", line 1168, in parse_desc_internal
    description = parse_desc(state, param.find('parameterdescription'))
  File "/m.css/doxygen/dox2html5.py", line 1627, in parse_desc
    parsed = parse_desc_internal(state, element)
  File "/m.css/doxygen/dox2html5.py", line 910, in parse_desc_internal
    add_css_class=add_css_class)
  File "/m.css/doxygen/dox2html5.py", line 1168, in parse_desc_internal
    description = parse_desc(state, param.find('parameterdescription'))
  File "/m.css/doxygen/dox2html5.py", line 1627, in parse_desc
    parsed = parse_desc_internal(state, element)
  File "/m.css/doxygen/dox2html5.py", line 910, in parse_desc_internal
    add_css_class=add_css_class)
  File "/m.css/doxygen/dox2html5.py", line 1168, in parse_desc_internal
    description = parse_desc(state, param.find('parameterdescription'))
  File "/m.css/doxygen/dox2html5.py", line 1627, in parse_desc
    parsed = parse_desc_internal(state, element)
  File "/m.css/doxygen/dox2html5.py", line 910, in parse_desc_internal
    add_css_class=add_css_class)
  File "/m.css/doxygen/dox2html5.py", line 1168, in parse_desc_internal
    description = parse_desc(state, param.find('parameterdescription'))
  File "/m.css/doxygen/dox2html5.py", line 1627, in parse_desc
    parsed = parse_desc_internal(state, element)
  File "/m.css/doxygen/dox2html5.py", line 910, in parse_desc_internal
    add_css_class=add_css_class)
  File "/m.css/doxygen/dox2html5.py", line 1168, in parse_desc_internal
    description = parse_desc(state, param.find('parameterdescription'))
  File "/m.css/doxygen/dox2html5.py", line 1627, in parse_desc
    parsed = parse_desc_internal(state, element)
  File "/m.css/doxygen/dox2html5.py", line 910, in parse_desc_internal
    add_css_class=add_css_class)
  File "/m.css/doxygen/dox2html5.py", line 1168, in parse_desc_internal
    description = parse_desc(state, param.find('parameterdescription'))
  File "/m.css/doxygen/dox2html5.py", line 1628, in parse_desc
    assert not parsed.templates and not parsed.params and not parsed.return_value and not parsed.return_values
AssertionError
```

**Comment by mosra** [comment]
Hi, sorry about the assertion! :)

These assertions are not meant to fire during common usage and are more for internal state consistency checks, so that's why the lack of context. As the [troubleshooting guide](https://mcss.mosra.cz/doxygen/#generating-takes-too-long-crashes-asserts-or-generally-fails) mentions, there's a `--debug` option for the script that prints what file is currently processed (it's spamming the output quite a lot, which is why it's off by default). Then, if you could send me the XML file which gets mentioned last before the assert (my e-mail is mosra@centrum.cz if you don't want to upload it publicly), I should be able to tell what's causing the assertion and, depending on how the input looks, suggest a workaround on your side or handle the special case / Doxygen featurebug on the script side. Doxygen is full of nasty surprises and since I've not witnessed an assert in this particular place yet I assume it's another ugly corner case that I didn't think of yet.

Thanks in advance!

**Comment by mosra** [comment]
Hi! Just wanted to give you a heads-up about this, as I don't think I received any e-mail from you with the details yet. Thanks again! :)

**Comment by mosra** [comment]
Closing as we never got to the actual cause of the assertion and thus I don't know what to fix. If you ever manage to make a publishable repro case, let me know :)
